export const types = {
  MINTED_NFTS_COUNT: "GET_MINTED_NFTS",
  SET_WALLET_CONNECTED: "SET_WALLET_CONNECTED",
  WALLET_ADDRESS: "WALLET_ADDRESS",
  CONNECT_WALLET_BTN_LOADING: "CONNECT_WALLET_BTN_LOADING",
  CREATE_VOUCHER: "CREATE_VOUCHER",
  VOUCHER_LOADING: "VOUCHER_LOADING",
  VOUCHER_RECIEVED: "VOUCHER_RECIEVED",
};
