name: Build and deploy Frontend Application to AWS EC2

on:
  push:
    branches:
      - dev

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    #needs: Gate-Status
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install    
      
    - name: Generate build
      run: |
        CI=false npm run build
        ls
    
    - name: directory files
      run: |
         ls
         pwd
      
#     - name: Copy Env File
#       run: |
#            tar -czvf build.tar build/
           
#     - name: Moving Artifact To Server
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         port: ${{ secrets.PORT }}
#         key: ${{ secrets.KEY }}
#         source: "build.tar"
#         target: "/var/www/now-front-stage" 
#     - name: Setting UP Things For Deployment
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.KEY }}
#         port: ${{ secrets.PORT }}
#         script: |
#          # whoami
         
#          cd /var/www/now-front-stage
#          rm -rf build
#          tar -zxvf build.tar
